### PR TITLE
Added 10 new rooms and GitHub Workflow, few changes

### PR DESCRIPTION
**Pull request by KoutaChan**
## Changes
- Added new 10 rooms
  - Lava-Skulls-3
  - Altar-6
  - Redstone-Skull-3
  - Crypts-1
  - Sewer-7
  - Slime-5
  - Double-Stair-3
  - Draw-Bridge-6
  - Four-Banner-1
  - Trinity-4 (probably work)
- Added Dueces-3 stonk ([Suggestion](https://discord.com/channels/804143990869590066/862628208414687252/957201648416067625))
- Fixes teleport pads room detection
- Added new Redstone-Key waypoint for Redstone-Key-3
- [Added a GitHub Workflow to automate the build process using Gradle](https://github.com/KoutaChan/DungeonRoomsMod/pull/1) (@Xmarmalade)

## Want to download? (Require Github account)
- [Download (artifact)](https://github.com/KoutaChan/DungeonRoomsMod/suites/16198082430/artifacts/925082037) [[View Github Actions log](https://github.com/KoutaChan/DungeonRoomsMod/actions/runs/6195289899)] (used the GitHub Action. it's very safe) 
- [Download (via nightly.link)](https://nightly.link/KoutaChan/DungeonRoomsMod/actions/runs/6195289899/artifact.zip) (don't need to GitHub account)
- [Download latest success build (via nightly.link)](https://nightly.link/KoutaChan/DungeonRoomsMod/workflows/gradle/3.x/artifact.zip)

## Screenshots
- Lava-Skulls-3

- Altar-6

- Redstone-Skull-3

- Crypts-1

- Sewer-7

- Double-Stair-3

- Slime-5

- Draw-Bridge-6

- Four-Banner-1 (probably this room is rare?)

### CODE REVIEW

**Comment by KoutaChan** [comment]
I'm released jar:
https://github.com/KoutaChan/DungeonRoomsMod/releases/tag/release-jar

**Comment by TreBoi** [comment]
A. How do I know this isn't a rat to download
B. If i wanna replace my mod with his update which download do I install?

**Comment by KoutaChan** [comment]
> A. How do I know this isn't a rat to download 
B. If i wanna replace my mod with his update which download do I install?

A. Any Java files have not been updated/added and are built from GitHub actions so it's safe (check it yourself)
B. since didn't push any new commits, all the same zip.

**Comment by Quantizr** [comment]
Thank you for contributing! As I’m away from my laptop for the next 5 days or so, could you please update the version number in build.gradle and DungeonRooms.java to 3.4.0 and commit. I will merge after and release with credit to you.

**Comment by KoutaChan** [comment]
> Thank you for contributing! As I’m away from my laptop for the next 5 days or so, could you please update the version number in build.gradle and DungeonRooms.java to 3.4.0 and commit. I will merge after and release with credit to you.

done

**Pull request merged**
